version: '3.8'

services:
  app:
    build: .
    container_name: audiolibri-editor
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REPO_OWNER=${REPO_OWNER}
      - REPO_NAME=${REPO_NAME}
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped